/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xperad' at '15/06/14 15:27' with Gradle 2.5-20150605053008+0000
 *
 * @author xperad, @date 15/06/14 15:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
